apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: nc-esp-stg-default
spec:
  # kubelet:
  #   podsPerCore: 2
  #   maxPods: 20
  #   systemReserved:
  #       cpu: 100m
  #       memory: 100Mi
  #       ephemeral-storage: 1Gi
  #   kubeReserved:
  #       cpu: 200m
  #       memory: 100Mi
  #       ephemeral-storage: 3Gi
  #   evictionHard:
  #       memory.available: 5%
  #       nodefs.available: 10%
  #       nodefs.inodesFree: 10%
  #   evictionSoft:
  #       memory.available: 500Mi
  #       nodefs.available: 15%
  #       nodefs.inodesFree: 15%
  #   evictionSoftGracePeriod:
  #       memory.available: 1m
  #       nodefs.available: 1m30s
  #       nodefs.inodesFree: 2m
  #   evictionMaxPodGracePeriod: 60
  #   imageGCHighThresholdPercent: 85
  #   imageGCLowThresholdPercent: 80
  #   cpuCFSQuota: true
  #   clusterDNS: ["10.0.1.100"]
  # Required, resolves a default ami and userdata
  # amiFamily: AL2

  # Required, discovers subnets to attach to instances
  # Each term in the array of subnetSelectorTerms is ORed together
  # Within a single term, all conditions are ANDed
  subnetSelectorTerms:
    # Select on any subnet that has the "karpenter.sh/discovery: eks-ezwel-sandbox"
    # AND the "environment: test" tag OR any subnet with ID "subnet-09fa4a0a8f233a921"
    - tags:
        karpenter.sh/discovery: 'eks-esp-stg'
        environment: 'stg'
    # - id: subnet-09fa4a0a8f233a921

  # Required, discovers security groups to attach to instances
  # Each term in the array of securityGroupSelectorTerms is ORed together
  # Within a single term, all conditions are ANDed
  securityGroupSelectorTerms:
    # Select on any security group that has both the "karpenter.sh/discovery: eks-ezwel-sandbox" tag
    # AND the "environment: test" tag OR any security group with the "my-security-group" name
    # OR any security group with ID "sg-063d7acfb4b06c82c"
    - tags:
        karpenter.sh/discovery: 'eks-esp-stg'
        environment: 'stg'
    # - name: my-security-group
    # - id: sg-063d7acfb4b06c82c

  # Optional, IAM role to use for the node identity.
  # The "role" field is immutable after EC2NodeClass creation. This may change in the
  # future, but this restriction is currently in place today to ensure that Karpenter
  # avoids leaking managed instance profiles in your account.
  # Must specify one of "role" or "instanceProfile" for Karpenter to launch nodes
  role: 'KarpenterNodeRole-eks-esp-stg'

  # Optional, IAM instance profile to use for the node identity.
  # Must specify one of "role" or "instanceProfile" for Karpenter to launch nodes
  # instanceProfile: 'KarpenterNodeInstanceProfile-eks-ezwel-sandbox'

  amiFamily: AL2
  # amiFamily: AL2023
  # Each term in the array of amiSelectorTerms is ORed together
  # Within a single term, all conditions are ANDed
  amiSelectorTerms:
    # Select on any AMI that has both the `karpenter.sh/discovery: eks-ezwel-sandbox`
    # AND `environment: test` tags OR any AMI with the name `my-ami` OR an AMI with
    # ID `ami-123`
    # - tags:
    #     karpenter.sh/discovery: eks-ezwel-sandbox
    #     environment: sandboxcle
    # AMAZON LINUX2
    # - id: ami-0348aa544e283a425
    # AMAZON LINUX2023
    # - id: ami-05be23b5a3f59423f
    # Select EKS optimized AL2023 AMIs with version `v20240807`. This term is mutually
    # exclusive and can't be specified with other terms.
    - alias: al2@latest

  # Optional, propagates tags to underlying EC2 resources
  # tags:
  #   team: team-a
  #   app: team-a-app

  # Optional, configures IMDS for the instance
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1 # This is changed to disable IMDS access from containers not on the host network
    httpTokens: required
  # Optional, configures storage devices for the instance
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 30Gi
        volumeType: gp3
        # iops: 10000
        encrypted: true
        # kmsKeyID: '1234abcd-12ab-34cd-56ef-1234567890ab'
        deleteOnTermination: true
        # throughput: 125
        # snapshotID: snap-0123456789

  # Optional, use instance-store volumes for node ephemeral-storage
  # instanceStorePolicy: RAID0

  # Optional, overrides autogenerated userdata with a merge semantic
  userData: |
    #!/bin/bash
    ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
    echo "Asia/Seoul" > /etc/timezone

  # Optional, configures detailed monitoring for the instance
  # detailedMonitoring: true

  # Optional, configures if the instance should be launched with an associated public IP address.
  # If not specified, the default value depends on the subnet's public IP auto-assign setting.
  # associatePublicIPAddress: true
