apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-resource-limits
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: require-cpu-memory-limits
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "모든 컨테이너에 CPU 및 메모리 requests/limits 값을 설정해야 합니다."
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    cpu: "?*"
                    memory: "?*"
                  requests:
                    cpu: "?*"
                    memory: "?*"