apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
        - key: 'arch-type'
          operator: Equal
          value: 'arm64'
      nodeSelector:
        arch-type: arm64
      containers:
        - name: nginx-container
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          image: nginx
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
              subPath: Asia/Seoul
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo
